name: Export Size
on:
  pull_request:
    branches:
      - main

jobs:
  size:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: antfu/export-size-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: .stacks/core/actions,.stacks/core/arrays,.stacks/core/auth,.stacks/core/build,.stacks/core/cache,.stacks/core/cli,.stacks/core/cloud,.stacks/core/config,.stacks/core/collections,.stacks/core/database,.stacks/core/datetime,.stacks/core/docs,.stacks/core/error-handling,.stacks/core/git,.stacks/core/lint,.stacks/core/modules,.stacks/core/notifications,.stacks/core/objects,.stacks/core/path,.stacks/core/realtime,.stacks/core/router,.stacks/core/security,.stacks/core/server,.stacks/core/storage,.stacks/core/strings,.stacks/core/testing,.stacks/core/types,.stacks/core/ui,.stacks/core/utils,.stacks/core/x-ray
